### Common

spring:

  application:
    name: Temperature
  profiles:
    active: dev

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

app:

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: com.qardio.assignment
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.unloadbrain.assignement.qardio.util.TemperatureSensorDataMessageDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.unloadbrain.assignement.qardio.util.TemperatureSensorDataMessageSerializer
    topic:
      temperature-sensor: TrackTemperature

  influxdb:
    url: http://localhost:8086
    user: admin
    pass: admin
    database: sensordata
    retention-policy: autogen
    read-timeout-in-seconds: 100

logging:
  level:
    root: INFO

---

### Dev profile

spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    com.unloadbrain: DEBUG

---

### Prod profile

spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    com.unloadbrain: INFO

---

### Integration test profile

spring:
  main:
    allow-bean-definition-overriding: true
  config:
    activate:
      on-profile: it






